### ISSUE TITLE
 I encountered a problem

### ISSUE THREAD

**Issue by shikingstar** [GreyGuoweiChen/RNA_virus_detector#1]
Hi！
when when I use " python predict.py --input test/test.fa --output test_results.fna" to do the analysis. I encountered a problem. Could you please help me to figure it out? Thank you very much.
![OM9Y{ `ZKNQE{QC260@ 5 7](https://user-images.githubusercontent.com/55352760/182509230-73bcde37-6886-4153-b507-22bacaef46ea.png)

**Comment by GreyGuoweiChen** [comment]
@shikingstar
Hi shikingstar,
I do not think this is the bug of the code. Following the error report, HMMer fails to access the HMMer model. You could try give the permission to the hmmer model file by 
`$ chmod 754 ref/RNA_virus.hmm`
or even
`$ chmod 775 ref/RNA_virus.hmm`
If this is not help, please check the HMMer version, which should be 3.3.2. Reinstall the HMMer might help as well.
