### ISSUE TITLE
Will Virbot have option to select th gentic code, such as the mold mitochondrial genetic code for translation. And etc.

### ISSUE THREAD

**Issue by permia** [GreyGuoweiChen/RNA_virus_detector#16]
Hi, Virbot is a covenient tool to find RNA viruses in the assembled contigs quickly.  I used it to quick-check the viruses in the sample. But here may be some small demands from me or other users.

1. Will Virbot have option to select th gentic code, such as the mold mitochondrial genetic code for translation, because of some RNA virus replicated in mitochodria.

2. If an output directory has been existed already, Virbot will report errors. 

3. Can I add customed HMM file to the database?

4. Is there any plan to including other viral protein except RdRp in the database?

**Comment by GreyGuoweiChen** [comment]
Hello Permia,

Thanks for your suggestions. 

1, Currently, VirBot relies on the well-developed gene prediction tool, Prodigal in meta mode, which seems to use the code 11 as default and does not allowed to changed it. Given that Prodigal has been validated  in multiple scenarios, we do not generated the proteins by ourself. As I know, the usage of alternative genetic code is not prevailing among RNA viruses. (Neri, Uri, et al. "Expansion of the global RNA virome reveals diverse clades of bacteriophages." Cell 185.21 (2022): 4023-4037.)

2, Yep, please designated a new output directory.

3, Owing that the adaptive cutoff of each HMM has a decisive effect on performance, we do not accept new HMM now.

4, VirBot is built on both RdRP and other viral proteins.
