### ISSUE TITLE
FileNotFoundError: VB_diamond.out not found

### ISSUE THREAD

**Issue by Wen1953** [GreyGuoweiChen/RNA_virus_detector#2]
Hi, I'm trying to use VirBot but when I run it seems to get this error:
#python VirBot.py --input test/test_input.fa --output VB_result --sen

#####
Traceback (most recent call last):
  File "/home/veronica/Programas/virbot/RNA_virus_detector/VirBot.py", line 375, in <module>
    predict(output_dir=f"{output_dir}/",
  File "/home/veronica/Programas/virbot/RNA_virus_detector/VirBot.py", line 318, in predict
    proteins = parse_diamond_blastx(temp_dir + "VB_diamond.out", proteins)
  File "/home/veronica/Programas/virbot/RNA_virus_detector/VirBot.py", line 207, in parse_diamond_blastx
    with open(filename,'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'VB_result/tmp/VB_diamond.out'
#####

I try the same with my data and I got the same result. I'm not sure if the version of diamond could be affecting? I have diamond version 0.9.14 installed thought conda.

**Comment by Wen1953** [comment]
I change the diamond version to 2.1.5 thought compiling from source and it work!.
https://github.com/bbuchfink/diamond/wiki/2.-Installation
![imagen](https://user-images.githubusercontent.com/89021119/225678058-a689b973-b184-4291-8d12-72be12bebbb3.png)

**Comment by RHaagmans** [comment]
Just wanted to add that I created a conda environment according to the instructions, and I ran into the same issue. It looks to me like some of the depencencies of recent Diamond versions are only available via the conda-forge channel... 

By adding conda-forge to the channel list, I managed to install Diamond 2.1.8:

`conda create -n virbot -c bioconda prodigal hmmer diamond python=3 pandas`

For increased reproducibility, perhaps the version numbers of prodigal, hmmer and diamond, or the complete conda environment, recommended for use with VirBot could be added to the readme?
